# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teamscore_oppid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='team_proj_diff',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='team_pts_diff',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
