# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170824_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='oppAbbv',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamscore',
            name='oppName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamscore',
            name='oppTotalPts',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='teamscore',
            name='opp_liveproj',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
