# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170824_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscore',
            name='team_ip',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_pmr',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_ytp',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
