# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170824_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscore',
            name='oppTotalPts',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='opp_liveproj',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_ip',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_liveproj',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_pmr',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_proj_diff',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_pts_diff',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team_ytp',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='tmTotalPts',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
